"""
HEAT RISK DEMO — deterministic synthetic scenarios
==================================================
The demo exists so a reviewer, judge or municipal stakeholder can see the
COMPLETE warning product — current conditions, a 3–5 day outlook, thermal
stress, vulnerability, health-impact indication, actions and notification
previews — with no network, no credentials and no live weather provider.

Hard rules (enforced by tests/test_demo_scenarios.py):

* **Deterministic.** Every number is a pure function of (scenario, zone,
  day, hour). No RNG, no wall clock: the scenario clock is FIXED at
  2026-05-18 06:00 Asia/Kolkata and clearly labelled as an intentional
  scenario timestamp, so "Day +3" always means the same date.
* **Labelled everywhere.** Every payload carries ``is_demo: true`` and the
  literal disclaimer below; nothing here may be presented as a live
  forecast, an observation, or an official IMD/AQI/mortality product.
* **Real physics, synthetic weather.** Scenario temperatures/humidity/wind/
  radiation feed the same HTSI and IMD-persistence code paths as live data
  (core/htsi.py, core/coupled.detect_heatwaves), against the REAL fixed
  1991–2020 climate normals shipped in data/climatology_normals.json. The
  normals are genuine; the weather is not, and says so.
* **Offline.** Nothing in this module performs I/O against a network
  provider. It only reads the committed climatology JSON.

Scenario presets (each shows a different part of normal → watch → warning →
severe without editing source code):

    monsoon-break        cooler, cloudier, near/below-normal — Normal & Watch
    dry-extreme          classic dry heatwave building to a SEVERE IMD
                         episode exactly at lead times 3–5
    humid-dangerous      dangerous WBGT while the IMD Tmax rule stays quiet —
                         the "temperature alone is not enough" lesson
    heat-plus-pollution  severe heat coinciding with hazardous PM2.5 —
                         joint heat+air load escalation
"""
from __future__ import annotations

import math
from typing import Any

import numpy as np
import pandas as pd

from core import config
from core.coupled import _apply_coupling, aqi_band, climatology_normal, load_climatology, ncr_zones
from core.htsi import HTSI_BANDS, compute_htsi_frame, htsi_band, htsi_score
from core.warnings import DEMO_DISCLAIMER, build_warning_rows, warnings_meta

# --------------------------------------------------------------------------- #
# 1. Fixed scenario clock — deliberate, documented, never `now()`
# --------------------------------------------------------------------------- #

DEMO_ISSUED_AT_LOCAL = pd.Timestamp("2026-05-18 06:00")   # tz-naive Asia/Kolkata
DEMO_TIMEZONE = config.TIMEZONE                            # Asia/Kolkata
DEMO_DAYS = 6                                              # issue day + 5 forecast days (leads 0..5)

# The canonical disclaimer text lives in core.warnings (DEMO_DISCLAIMER) so
# demo payloads and notification messages always quote the identical sentence.

DEMO_DATA_SOURCE_TEMPLATE = (
    "synthetic demo scenario '{scenario}' — deterministic, offline, generated by core/demo.py"
)

# --------------------------------------------------------------------------- #
# 2. Scenario catalogue
# --------------------------------------------------------------------------- #
# Peak-hour parameters per day index 0..5 for a REFERENCE zone; per-zone
# offsets (ZONE_HEAT_OFFSET) add deterministic spatial variety so zones show
# different risk levels in the same scenario.

SCENARIOS: dict[str, dict[str, Any]] = {
    "monsoon-break": {
        "label": "Monsoon break — cooler, near-normal stress",
        "tagline": "What NORMAL and WATCH conditions look like.",
        "summary": (
            "Pre-monsoon squall line brings cloud, breeze and rain showers. Tmax stays "
            "6–8 °C BELOW the 1991–2020 normal: thermal stress is Normal in most zones "
            "and Watch in the densest core. No heatwave candidate fires."
        ),
        "teaching_points": [
            "Normal/Watch levels exist so operators can see the quiet state too",
            "Cloud and wind cut the globe temperature — radiation matters, not just Tmax",
            "A below-normal day can still carry modest WBGT in full sun",
        ],
        "expected": {"alert_levels": ["routine", "watch"], "heatwave_episode": False},
        "tmax": [33.0, 32.4, 33.6, 34.2, 33.8, 33.0],
        "tmin_offset": [5.8, 5.4, 6.0, 6.2, 6.0, 5.6],
        "rh_at_peak": [52.0, 56.0, 50.0, 48.0, 50.0, 54.0],
        "rh_overnight": [88.0, 92.0, 87.0, 85.0, 86.0, 90.0],
        "solar_peak": [520.0, 430.0, 560.0, 610.0, 540.0, 470.0],
        "wind_base_kmh": [15.0, 17.0, 14.0, 13.0, 14.0, 16.0],
        "pm25_base": [30.0, 24.0, 32.0, 35.0, 31.0, 27.0],
        "precip_day_mm": [0.0, 4.2, 0.0, 0.0, 0.8, 1.6],
    },
    "dry-extreme": {
        "label": "Dry extreme heatwave — severe at lead 3–5",
        "tagline": "The classic 3–5 day advance-warning case.",
        "summary": (
            "A dry heat dome builds over the region. Tmax climbs from 43 °C on the issue "
            "day to 47.6 °C by Day +4 — departures of +6 to +7.4 °C over the fixed "
            "1991–2020 normal. Days +2 to +5 form a declared SEVERE heatwave episode "
            "(≥2-day persistence), so warnings carry real lead time of 3, 4 and 5 days."
        ),
        "teaching_points": [
            "Lead times 3/4/5 days on a declared episode — the product's core promise",
            "Two-day persistence rule: the first candidate day stays an early watch",
            "Dry air keeps wet-bulb/WBGT far below the Heat Index — the metrics disagree because they answer different questions",
        ],
        "expected": {"alert_levels": ["warning", "severe"], "heatwave_episode": True},
        "tmax": [42.4, 44.0, 45.2, 46.3, 47.0, 46.6],
        "tmin_offset": [12.4, 12.8, 13.0, 12.6, 12.2, 12.8],
        "rh_at_peak": [22.0, 19.0, 16.0, 14.0, 12.0, 13.0],
        "rh_overnight": [36.0, 33.0, 30.0, 28.0, 27.0, 29.0],
        "solar_peak": [980.0, 1010.0, 1040.0, 1060.0, 1050.0, 1030.0],
        "wind_base_kmh": [9.0, 8.0, 7.0, 7.5, 8.5, 9.5],
        "pm25_base": [58.0, 66.0, 78.0, 92.0, 88.0, 74.0],
        "precip_day_mm": [0.0] * 6,
    },
    "humid-dangerous": {
        "label": "Humid dangerous heat — WBGT-driven severe risk",
        "tagline": "Why temperature alone is not enough.",
        "summary": (
            "Moist maritime air keeps Tmax at 35–38 °C — BELOW the IMD heatwave absolute "
            "threshold, so no heatwave episode is declared — but humidity of 68–82 % at "
            "peak drives estimated WBGT past 33–35 °C and the HTSI into Severe. Sweat "
            "stops evaporating; the dry-bulb number hides the danger."
        ),
        "teaching_points": [
            "IMD Tmax label says None/Watch while thermal stress says Severe — read both",
            "Wet-bulb physics: humidity dominates WBGT when radiation is modest",
            "Health-impact indicator escalates from the thermal channel, not the heatwave channel",
        ],
        "expected": {"alert_levels": ["warning", "severe"], "heatwave_episode": False},
        "tmax": [35.4, 36.0, 36.6, 37.2, 37.8, 37.4],
        "tmin_offset": [6.2, 6.0, 5.8, 5.6, 5.6, 5.8],
        "rh_at_peak": [68.0, 70.0, 72.0, 74.0, 76.0, 74.0],
        "rh_overnight": [90.0, 91.0, 92.0, 93.0, 94.0, 92.0],
        "solar_peak": [720.0, 700.0, 680.0, 660.0, 640.0, 660.0],
        "wind_base_kmh": [10.0, 11.0, 12.0, 11.0, 9.0, 10.0],
        "pm25_base": [46.0, 50.0, 54.0, 58.0, 55.0, 49.0],
        "precip_day_mm": [0.0] * 6,
    },
    "heat-plus-pollution": {
        "label": "Severe heat + hazardous air pollution",
        "tagline": "Compound exposure: the joint heat+air load escalates.",
        "summary": (
            "A stagnant, near-windless spell traps dust and combustion PM2.5 under strong "
            "heat. Tmax approaches 48 °C in the densest zones (a severe heatwave episode on "
            "Days +2 to +5) WHILE PM2.5 peaks push the indicative Indian AQI into the 400s. "
            "The joint heat+air load band reaches Severe, lifting recommended actions a level."
        ),
        "teaching_points": [
            "Concentration AQI stays separate from the parameterised joint load",
            "Stagnant wind raises both WBGT (less convective cooling) and PM2.5",
            "Escalation rule: severe air load + thermal ≥ warning ⇒ severe alert level",
        ],
        "expected": {"alert_levels": ["warning", "severe"], "heatwave_episode": True},
        "tmax": [41.8, 43.4, 45.0, 46.2, 46.9, 46.0],
        "tmin_offset": [11.6, 11.2, 10.8, 10.4, 10.2, 10.8],
        "rh_at_peak": [30.0, 27.0, 24.0, 22.0, 20.0, 23.0],
        "rh_overnight": [48.0, 45.0, 42.0, 40.0, 38.0, 42.0],
        "solar_peak": [880.0, 900.0, 910.0, 920.0, 900.0, 870.0],
        "wind_base_kmh": [6.0, 5.0, 4.5, 4.0, 4.5, 6.5],
        "pm25_base": [95.0, 150.0, 210.0, 260.0, 290.0, 240.0],
        "precip_day_mm": [0.0] * 6,
    },
}

# Deterministic per-zone heat offsets (urban core warmer, greener fringe cooler).
ZONE_HEAT_OFFSET: dict[str, float] = {
    "central-delhi": 1.1,
    "north-delhi": 0.5,
    "east-delhi": 0.8,
    "south-delhi": 0.2,
    "noida": 0.4,
    "greater-noida": -0.5,
    "gurugram": 0.7,
    "faridabad": -0.2,
}

SCENARIO_ORDER: tuple[str, ...] = (
    "monsoon-break", "dry-extreme", "humid-dangerous", "heat-plus-pollution",
)


def scenario_ids() -> tuple[str, ...]:
    return SCENARIO_ORDER


def scenario_meta(scenario_id: str) -> dict[str, Any]:
    if scenario_id not in SCENARIOS:
        raise KeyError(scenario_id)
    scenario = SCENARIOS[scenario_id]
    return {
        "id": scenario_id,
        "label": scenario["label"],
        "tagline": scenario["tagline"],
        "summary": scenario["summary"],
        "teaching_points": list(scenario["teaching_points"]),
        "expected": scenario["expected"],
        "issued_at_local": DEMO_ISSUED_AT_LOCAL.strftime("%Y-%m-%dT%H:%M"),
        "issued_at_note": (
            "Fixed scenario timestamp (intentional): the demo clock never moves, so "
            "'Day +3' is always 2026-05-21 regardless of when you open the demo."
        ),
        "timezone": DEMO_TIMEZONE,
        "forecast_days": DEMO_DAYS,
        "data_source": DEMO_DATA_SOURCE_TEMPLATE.format(scenario=scenario_id),
        "is_demo": True,
        "is_synthetic": True,
        "demo_disclaimer": DEMO_DISCLAIMER,
    }


# --------------------------------------------------------------------------- #
# 3. Deterministic hourly generation — pure function, no clock, no network
# --------------------------------------------------------------------------- #

def _diurnal_shape(hour: float) -> float:
    """1.0 at 15:00 local peak, −1.0 at 03:00 trough."""
    return math.cos((hour - 15.0) * 2.0 * math.pi / 24.0)


def _solar_shape(hour: float) -> float:
    """Clear-ish sky bell from 06:00 to 18:00, peaking at noon."""
    if hour <= 6.0 or hour >= 18.0:
        return 0.0
    return math.sin(math.pi * (hour - 6.0) / 12.0)


def _hour_values(scenario: dict[str, Any], day_index: int, hour: float, zone_offset: float) -> dict[str, float]:
    tmax = scenario["tmax"][day_index] + zone_offset
    tmin = tmax - scenario["tmin_offset"][day_index]
    shape = _diurnal_shape(hour)
    temp = (tmax + tmin) / 2.0 + (tmax - tmin) / 2.0 * shape

    rh_peak = max(8.0, scenario["rh_at_peak"][day_index] - 1.6 * zone_offset)
    rh_night = min(97.0, scenario["rh_overnight"][day_index] - 1.2 * zone_offset)
    rh_mid = (rh_night + rh_peak) / 2.0
    rh = rh_mid - (rh_mid - rh_peak) * ((shape + 1.0) / 2.0)

    solar = scenario["solar_peak"][day_index] * _solar_shape(hour)
    wind = max(1.0, scenario["wind_base_kmh"][day_index]
               + 2.6 * math.sin((hour - 13.0) * 2.0 * math.pi / 24.0)
               - 0.35 * abs(zone_offset))

    pm_base = scenario["pm25_base"][day_index] + 4.0 * abs(zone_offset)
    # Nighttime inversion peak around 03:00 + a small evening cooking bump.
    pm = pm_base * (1.0 + 0.42 * math.cos((hour - 3.0) * 2.0 * math.pi / 24.0)
                    + 0.10 * math.exp(-((hour - 20.0) / 1.6) ** 2))

    precip = 0.0
    day_precip = scenario["precip_day_mm"][day_index]
    if day_precip > 0 and 15.0 <= hour <= 20.0:
        precip = day_precip / 5.0 * max(0.0, math.sin(math.pi * (hour - 15.0) / 5.0))

    return {
        "temp_c": round(min(temp, 54.0), 2),
        "rh_pct": round(min(max(rh, 5.0), 99.0), 1),
        "wind_kmh": round(wind, 2),
        "solar_wm2": round(max(0.0, solar), 1),
        "pm25_ugm3": round(max(6.0, pm), 1),
        "precip_mm": round(precip, 2),
    }


def scenario_frame(scenario_id: str, zones: pd.DataFrame | None = None) -> pd.DataFrame:
    """Full deterministic hourly frame for a scenario: 8 zones × 6 days × 24 h.

    Column-compatible with ``core.coupled`` frames (so ncr_daily /
    detect_heatwaves / HTSI consume it unchanged) plus explicit demo labels.
    """
    if scenario_id not in SCENARIOS:
        raise KeyError(f"unknown demo scenario '{scenario_id}' — see /demo/scenarios")
    scenario = SCENARIOS[scenario_id]
    zone_table = ncr_zones() if zones is None else zones

    # The scenario clock starts at midnight of the issue day; the 06:00
    # issuance time still drives every lead-time calculation (lead_hours to
    # Day +0's 15:00 peak is +9 h). Hours before 06:00 on Day +0 stand in for
    # the analysis window a real 06:00 bulletin would summarise.
    hours = pd.date_range(start=DEMO_ISSUED_AT_LOCAL.normalize(), periods=DEMO_DAYS * 24, freq="h")
    rows: list[dict[str, Any]] = []
    for zone in zone_table.to_dict("records"):
        offset = ZONE_HEAT_OFFSET.get(str(zone["zone_id"]), 0.0)
        for ts in hours:
            day_index = (ts.normalize() - DEMO_ISSUED_AT_LOCAL.normalize()).days
            values = _hour_values(scenario, day_index, ts.hour + ts.minute / 60.0, offset)
            rows.append({
                "zone_id": zone["zone_id"],
                "zone_name": zone["zone_name"],
                "lat": zone["lat"],
                "lon": zone["lon"],
                "timestamp_local": ts,
                **values,
                "pm10_ugm3": round(values["pm25_ugm3"] * 1.55, 1),
                "surface_pressure_hpa": 1004.0 - 0.6 * day_index,
            })

    frame = _apply_coupling(pd.DataFrame(rows))
    frame["data_source"] = DEMO_DATA_SOURCE_TEMPLATE.format(scenario=scenario_id)
    frame["is_synthetic"] = True
    frame["is_demo"] = True
    frame["scenario_id"] = scenario_id
    frame["issued_at"] = DEMO_ISSUED_AT_LOCAL.strftime("%Y-%m-%dT%H:%M")
    frame["fetched_at"] = "2026-05-18T00:30:00+00:00"   # fixed scenario issuance, UTC
    return frame.sort_values(["zone_id", "timestamp_local"]).reset_index(drop=True)


# --------------------------------------------------------------------------- #
# 4. Payload builders (one per API route; also used by scripts/export_static)
# --------------------------------------------------------------------------- #

def _envelope(scenario_id: str, **extra: Any) -> dict[str, Any]:
    base = {
        "is_demo": True,
        "is_synthetic": True,
        "demo_disclaimer": DEMO_DISCLAIMER,
        "scenario": scenario_meta(scenario_id),
        "data_source": DEMO_DATA_SOURCE_TEMPLATE.format(scenario=scenario_id),
        "quality_state": "demo-synthetic",
    }
    base.update(extra)
    return base


def scenarios_payload() -> dict[str, Any]:
    """Catalogue of every preset — what the demo selector renders."""
    return {
        "is_demo": True,
        "is_synthetic": True,
        "demo_disclaimer": DEMO_DISCLAIMER,
        "issued_at_local": DEMO_ISSUED_AT_LOCAL.strftime("%Y-%m-%dT%H:%M"),
        "timezone": DEMO_TIMEZONE,
        "forecast_days": DEMO_DAYS,
        "lead_days_available": list(range(0, DEMO_DAYS)),
        "zone_count": int(len(ncr_zones())),
        "band_vocabulary": [
            {"band": band, "colour": colour, "htsi_min": lo, "meaning": meaning}
            for lo, band, colour, meaning in HTSI_BANDS
        ],
        "scenarios": [scenario_meta(sid) for sid in SCENARIO_ORDER],
        "how_to_read": (
            "Pick a scenario, then read the outlook (lead times), thermal stress (HTSI + "
            "quality flags), impact (vulnerability + health-impact status), actions and "
            "notification previews. Every value is synthetic and labelled; the physics and "
            "the decision rules are the same code that runs on live data."
        ),
    }


def zones_payload() -> dict[str, Any]:
    """Zone registry + synthetic vulnerability profiles + cooling-centre layer."""
    from core.warnings import ZONE_PROFILE_SOURCE, VULNERABILITY_FORMULA, zone_profiles_with_geo

    profiles = zone_profiles_with_geo()
    data = []
    for row in profiles.to_dict("records"):
        data.append({
            "zone_id": row["zone_id"],
            "zone_name": row["zone_name"],
            "lat": round(float(row["lat"]), 4),
            "lon": round(float(row["lon"]), 4),
            "population": int(row["population"]),
            "pop_density_km2": int(row["pop_density_km2"]),
            "elderly_pct": float(row["elderly_pct"]),
            "outdoor_worker_pct": float(row["outdoor_worker_pct"]),
            "illiteracy_pct": float(row["illiteracy_pct"]),
            "cooling_centre_count": int(row["cooling_centre_count"]),
            "cooling_access_score": float(row["cooling_access_score"]),
            "vulnerability_score": float(row["vulnerability_score"]),
            "vulnerability_level": row["vulnerability_level"],
            "vulnerability_source": row["vulnerability_source"],
            "cooling_centres": list(row["cooling_centres"]),
        })
    return {
        "is_demo": True,
        "is_synthetic": True,
        "demo_disclaimer": DEMO_DISCLAIMER,
        "count": len(data),
        "vulnerability_formula": VULNERABILITY_FORMULA,
        "vulnerability_source": ZONE_PROFILE_SOURCE,
        "granularity_note": (
            "Demo zones are ~10 km model grid points standing in for municipal zones/wards. "
            "A zone value is not a street-level observation."
        ),
        "cooling_centre_note": (
            "Cooling centres are synthetic placeholders so the GIS layer can be reviewed; "
            "replace with a municipal GIS feed before any operational use."
        ),
        "data": data,
    }


def forecast_payload(scenario_id: str, zone_id: str | None = None) -> dict[str, Any]:
    """Meteorological forecast view: daily summaries with lead times + full hourly."""
    frame = scenario_frame(scenario_id)
    if zone_id is not None:
        frame = frame[frame["zone_id"] == zone_id].copy()
        if frame.empty:
            raise KeyError(zone_id)
    climatology = load_climatology()

    frame["date"] = frame["timestamp_local"].dt.date
    daily = (
        frame.groupby(["zone_id", "zone_name", "lat", "lon", "date"], as_index=False)
        .agg(
            tmax_c=("temp_c", "max"),
            tmin_c=("temp_c", "min"),
            rh_min_pct=("rh_pct", "min"),
            rh_mean_pct=("rh_pct", "mean"),
            wind_mean_kmh=("wind_kmh", "mean"),
            solar_max_wm2=("solar_wm2", "max"),
            precip_mm=("precip_mm", "sum"),
            pm25_mean_ugm3=("pm25_ugm3", "mean"),
            pm25_peak_ugm3=("pm25_ugm3", "max"),
            aqi_peak=("aqi_india", "max"),
            heat_aqi_load_peak=("heat_aqi_load", "max"),
        )
        .sort_values(["zone_id", "date"])
    )
    daily["aqi_band"] = [aqi_band(v) for v in daily["aqi_peak"]]
    daily["heat_aqi_load_band"] = [aqi_band(v) for v in daily["heat_aqi_load_peak"]]

    normals, departures = [], []
    for record in daily.to_dict("records"):
        normal, _gran = climatology_normal(climatology, record["zone_id"], record["date"])
        normals.append(round(normal, 1) if normal is not None else None)
        departures.append(round(record["tmax_c"] - normal, 1) if normal is not None else None)
    daily["normal_tmax_c"] = normals
    daily["departure_c"] = departures

    issue_date = DEMO_ISSUED_AT_LOCAL.normalize().date()
    daily["lead_days"] = [(pd.Timestamp(d).date() - issue_date).days for d in daily["date"]]
    daily["target_day_label"] = [f"Day +{lead}" for lead in daily["lead_days"]]
    daily["date"] = daily["date"].astype(str)

    daily_cols = [
        "zone_id", "zone_name", "lat", "lon", "date", "target_day_label", "lead_days",
        "tmax_c", "tmin_c", "rh_min_pct", "rh_mean_pct", "wind_mean_kmh", "solar_max_wm2",
        "precip_mm", "pm25_mean_ugm3", "pm25_peak_ugm3", "aqi_peak", "aqi_band",
        "heat_aqi_load_peak", "heat_aqi_load_band", "normal_tmax_c", "departure_c",
    ]
    daily_records = _clean_records(daily[daily_cols].round(
        {"tmax_c": 1, "tmin_c": 1, "rh_min_pct": 1, "rh_mean_pct": 1, "wind_mean_kmh": 1,
         "solar_max_wm2": 0, "precip_mm": 1, "pm25_mean_ugm3": 1, "pm25_peak_ugm3": 1}))

    hourly_cols = ["zone_id", "timestamp_local", "lead_days", "temp_c", "rh_pct", "wind_kmh",
                   "solar_wm2", "precip_mm", "pm25_ugm3", "aqi_india", "heat_aqi_load"]
    hourly = frame.copy()
    hourly["lead_days"] = [(ts.normalize() - DEMO_ISSUED_AT_LOCAL.normalize()).days
                           for ts in hourly["timestamp_local"]]
    # Hourly detail covers the issue day ("current conditions" chart); the
    # 5-day outlook is the daily table with explicit lead times. Keeping the
    # full 6×24 grid in every static payload would triple its size for curves
    # no screen renders.
    hourly = hourly[hourly["lead_days"] == 0]
    hourly["timestamp_local"] = hourly["timestamp_local"].dt.strftime("%Y-%m-%dT%H:%M")
    hourly_records = _clean_records(hourly[hourly_cols].round(
        {"temp_c": 1, "rh_pct": 0, "wind_kmh": 1, "solar_wm2": 0, "precip_mm": 1,
         "pm25_ugm3": 0, "aqi_india": 0, "heat_aqi_load": 0}))

    return _envelope(
        scenario_id,
        zone_id=zone_id,
        rows_daily=len(daily_records),
        rows_hourly=len(hourly_records),
        hourly_scope="issue day (Day +0) only — the daily table carries the full 5-day outlook",
        granularity_note=(
            "Zone-level model values (~10 km grid) — not ward-level observations."
        ),
        climatology_note=(
            "normal_tmax_c comes from the REAL fixed 1991–2020 normals "
            "(data/climatology_normals.json); the weather around it is synthetic."
        ),
        daily=daily_records,
        hourly=hourly_records,
    )


def thermal_payload(scenario_id: str, zone_id: str | None = None) -> dict[str, Any]:
    """HTSI view: daily thermal metrics + quality flags + issue-day hourly detail."""
    from core.htsi import HTSI_METADATA, QUALITY_DEFINITIONS, daily_htsi

    frame = scenario_frame(scenario_id)
    climatology = load_climatology()

    # Anomaly term of the HTSI = departure of the DAY's Tmax from the fixed
    # 1991–2020 normal, applied uniformly to every hour of that day (an
    # hour-by-hour departure would let overnight cooling erase the anomaly).
    frame["date"] = frame["timestamp_local"].dt.date
    daily_tmax = frame.groupby(["zone_id", "date"], sort=False)["temp_c"].max()
    departures_by_key: dict[tuple[str, Any], float] = {}
    for (zone_key, date_key), tmax_value in daily_tmax.items():
        normal, _gran = climatology_normal(climatology, zone_key, date_key)
        if normal is not None:
            departures_by_key[(zone_key, date_key)] = float(tmax_value) - float(normal)
    frame["departure_c"] = pd.Series(
        [departures_by_key.get((z, d), np.nan) for z, d in zip(frame["zone_id"], frame["date"])],
        index=frame.index, dtype="float64",
    )

    thermal_hourly = compute_htsi_frame(frame, departure_c=frame["departure_c"])
    # Recompute the score with the anomaly term for hourly rows too.
    scores = [htsi_score(w, d) for w, d in zip(thermal_hourly["wbgt_est_c"], thermal_hourly["departure_c"])]
    thermal_hourly["htsi_score"] = scores
    thermal_hourly["htsi_band"] = [htsi_band(s)["band"] for s in scores]

    daily = daily_htsi(thermal_hourly)
    # attach normals + rescore with the Tmax-vs-normal anomaly at the daily peak
    normals, grans, deps, rescored, anomaly_used = [], [], [], [], []
    for record in daily.to_dict("records"):
        normal, gran = climatology_normal(climatology, record["zone_id"], record["date"])
        dep = round(record["tmax_c"] - normal, 1) if normal is not None and record.get("tmax_c") is not None else None
        score = htsi_score(record.get("wbgt_est_peak_c"), dep)
        base = htsi_score(record.get("wbgt_est_peak_c"), None)
        normals.append(round(normal, 2) if normal is not None else None)
        grans.append(gran)
        deps.append(dep)
        rescored.append(score)
        anomaly_used.append(bool(score is not None and base is not None
                                 and abs(score - base) > 1e-9))
    daily["normal_tmax_c"] = normals
    daily["normal_granularity"] = grans
    daily["departure_c"] = deps
    daily["htsi_score"] = rescored
    daily["htsi_anomaly_used"] = anomaly_used
    daily["htsi_band"] = [htsi_band(s)["band"] for s in daily["htsi_score"]]
    daily["date"] = daily["date"].astype(str)
    issue_date = DEMO_ISSUED_AT_LOCAL.normalize().date()
    daily["lead_days"] = [(pd.Timestamp(d).date() - issue_date).days for d in daily["date"]]

    if zone_id is not None:
        daily = daily[daily["zone_id"] == zone_id].copy()
        thermal_hourly = thermal_hourly[thermal_hourly["zone_id"] == zone_id].copy()
        if daily.empty:
            raise KeyError(zone_id)

    daily_cols = [
        "zone_id", "date", "lead_days", "tmax_c", "normal_tmax_c", "normal_granularity",
        "departure_c", "hi_peak_c", "wbgt_est_peak_c", "wbgt_peak_quality", "wbgt_peak_inputs",
        "htsi_score", "htsi_band", "htsi_anomaly_used",
    ]
    hourly_view = thermal_hourly.copy()
    # Same scoping rule as the forecast payload: hourly detail for the issue
    # day only; every outlook day is covered by the daily thermal table.
    issue_day = DEMO_ISSUED_AT_LOCAL.normalize()
    hourly_view = hourly_view[hourly_view["timestamp_local"].dt.normalize() == issue_day]
    hourly_view["timestamp_local"] = hourly_view["timestamp_local"].dt.strftime("%Y-%m-%dT%H:%M")
    hourly_cols = ["zone_id", "timestamp_local", "temp_c", "rh_pct", "wind_kmh", "solar_wm2",
                   "wet_bulb_c", "globe_c", "heat_index_c", "wbgt_est_c", "wbgt_quality",
                   "htsi_score", "htsi_band"]
    return _envelope(
        scenario_id,
        zone_id=zone_id,
        method=HTSI_METADATA,
        quality_definitions=QUALITY_DEFINITIONS,
        wbgt_statement=(
            "wbgt_est_c is an ESTIMATED WBGT computed from scenario weather inputs with the "
            "ISO 7243 outdoor formula. It is not a measured globe-thermometer WBGT and must "
            "never be labelled as one."
        ),
        hourly_scope="issue day (Day +0) only — the daily table carries the full 5-day outlook",
        rows_daily=len(daily),
        rows_hourly=len(hourly_view),
        daily=_clean_records(daily[daily_cols]),
        hourly=_clean_records(hourly_view[hourly_cols].round(
            {"temp_c": 1, "rh_pct": 0, "wind_kmh": 1, "solar_wm2": 0, "wet_bulb_c": 1,
             "globe_c": 1, "heat_index_c": 1, "wbgt_est_c": 1})),
    )


def warnings_payload(scenario_id: str, zone_id: str | None = None) -> dict[str, Any]:
    """Operational 3–5 day advance-warning rows for a demo scenario."""
    frame = scenario_frame(scenario_id)
    if zone_id is not None:
        frame = frame[frame["zone_id"] == zone_id].copy()
        if frame.empty:
            raise KeyError(zone_id)
    climatology = load_climatology()
    rows = build_warning_rows(
        frame,
        issued_at=DEMO_ISSUED_AT_LOCAL,
        quality_state="demo-synthetic",
        data_source=DEMO_DATA_SOURCE_TEMPLATE.format(scenario=scenario_id),
        is_demo=True,
        scenario_id=scenario_id,
        climatology=climatology,
        fallback_reason=None,
    )
    lead_counts: dict[str, int] = {}
    level_counts: dict[str, int] = {}
    for row in rows:
        lead_counts[str(row["lead_days"])] = lead_counts.get(str(row["lead_days"]), 0) + 1
        level_counts[row["alert_level"]] = level_counts.get(row["alert_level"], 0) + 1
    payload = _envelope(
        scenario_id,
        zone_id=zone_id,
        rows=len(rows),
        lead_day_counts=lead_counts,
        alert_level_counts=level_counts,
        data=rows,
    )
    payload.update(warnings_meta(issued_at=DEMO_ISSUED_AT_LOCAL, climatology=climatology,
                                 is_demo=True, scenario_id=scenario_id))
    payload["rows"] = len(rows)
    return payload


def notifications_payload(scenario_id: str) -> dict[str, Any]:
    """Dry-run notification previews generated from this scenario's warnings."""
    from core.notify import plan_notifications

    rows = warnings_payload(scenario_id)["data"]
    plan = plan_notifications(rows, is_demo=True, scenario_id=scenario_id)
    return _envelope(scenario_id, **plan)


# --------------------------------------------------------------------------- #
# 5. Small shared helpers
# --------------------------------------------------------------------------- #

def _clean_records(df: pd.DataFrame) -> list[dict[str, Any]]:
    """JSON-safe records: NaN → None, numpy → python, timestamps → strings."""
    out = df.copy()
    for column in out.columns:
        if pd.api.types.is_datetime64_any_dtype(out[column]):
            out[column] = out[column].dt.strftime("%Y-%m-%dT%H:%M")
    out = out.astype(object).where(pd.notna(out), None)
    records = out.to_dict(orient="records")
    cleaned: list[dict[str, Any]] = []
    for record in records:
        cleaned.append({
            key: (value.item() if isinstance(value, np.generic) else value)
            for key, value in record.items()
        })
    return cleaned


__all__ = [
    "DEMO_DAYS", "DEMO_DISCLAIMER", "DEMO_ISSUED_AT_LOCAL", "DEMO_TIMEZONE",
    "SCENARIOS", "SCENARIO_ORDER", "ZONE_HEAT_OFFSET", "forecast_payload",
    "notifications_payload", "scenario_frame", "scenario_ids", "scenario_meta",
    "scenarios_payload", "thermal_payload", "warnings_payload", "zones_payload",
]


# --------------------------------------------------------------------------- #
if __name__ == "__main__":  # pragma: no cover — quick manual review
    for sid in SCENARIO_ORDER:
        payload = warnings_payload(sid)
        levels = payload["alert_level_counts"]
        leads = payload["lead_day_counts"]
        episodes = sum(1 for row in payload["data"] if row["is_heatwave_episode"])
        print(f"{sid:22s} rows={payload['rows']:3d} levels={levels} leads={leads} episode_rows={episodes}")
        worst = max(payload["data"], key=lambda r: (r["htsi_score"] or 0))
        print(f"{'':22s} worst: {worst['zone_name']} {worst['target_date']} HTSI={worst['htsi_score']} "
              f"WBGT={worst['wbgt_est_peak_c']} Tmax={worst['tmax_c']} dep={worst['departure_c']} "
              f"label={worst['heatwave_label']} level={worst['alert_level']}")
