"""
Bundle the project into a downloadable zip.

    python scripts/package.py                 # -> ../heatshield.zip
    python scripts/package.py --out /tmp/x.zip --label phases-1-2

Excludes everything regenerable (venv, caches, raw dumps, node_modules, .env)
so the archive stays small and clean. Re-run after each phase to refresh it.
"""
from __future__ import annotations

import argparse
import sys
import zipfile
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]

EXCLUDE_DIRS = {
    ".venv", "venv", "env", "__pycache__", ".pytest_cache", ".mypy_cache",
    # NB: ".vscode" is deliberately NOT excluded — launch.json / tasks.json are
    # part of the project now (F5 runs the full stack), so they ship with it.
    ".ruff_cache", "node_modules", ".git", ".idea",
    "cache", "logs", "dist", "build", ".next", ".turbo", "target",
}
EXCLUDE_GLOBS = (
    "*.pyc", "*.pyo", "*.egg-info", "*.zip", "*.tar.gz", "*.apk", "*.aab",
    ".DS_Store", "Thumbs.db", ".env", "*.log",
)
# Regenerable data: keep the tiny seed files, drop the downloaded dumps
EXCLUDE_DATA = {"raw", "cache"}
# heavy intermediate OSM dumps: regenerable, hundreds of MB
EXCLUDE_HEAVY = {"green.json", "buildings.json", "kolkata_datameet.json"}
# never drop these from data/raw or data/cache.
# .parquet matters more than it looks: it is the 36 kB forecast cache, and
# shipping it is what lets a fresh download render a full dashboard on first run
# with NO internet. Without it get_forecast() has nothing to read and the app
# looks broken offline.
KEEP_DATA_SUFFIX = {".xlsx", ".xls", ".csv", ".parquet"}


def should_skip(path: Path) -> bool:
    rel = path.relative_to(BASE)

    # data/raw and data/cache are judged FIRST, before the generic directory
    # exclusions below. EXCLUDE_DIRS contains "cache", so if this ran after it
    # every file in data/cache — including the 36 kB forecast cache that makes a
    # fresh download work offline — would be dropped and this rule would be dead
    # code.
    #
    # data/raw/*.json and data/cache/* are regenerated by the pipeline, BUT:
    #   - the official Census xlsx cannot be re-downloaded (censusindia.gov.in
    #     is defunct; Wayback is the only route), and
    #   - the forecast cache lets a fresh install render with no network.
    if len(rel.parts) >= 2 and rel.parts[0] == "data" and rel.parts[1] in EXCLUDE_DATA:
        if path.suffix.lower() in KEEP_DATA_SUFFIX:
            return False
        return not path.name.startswith(".gitkeep")

    if any(part in EXCLUDE_DIRS for part in rel.parts):
        return True
    if any(path.match(g) for g in EXCLUDE_GLOBS):
        return True
    # multi-hundred-MB OSM dumps — rebuild with scripts/build_wards.py
    if path.name in EXCLUDE_HEAVY:
        return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(BASE.parent / "heatshield.zip"))
    ap.add_argument("--label", default="", help="e.g. phases-1-2 (stamped into the filename)")
    args = ap.parse_args()

    out = Path(args.out)
    if args.label and out.name == "heatshield.zip":
        out = out.with_name(f"heatshield-{args.label}.zip")

    files = sorted(p for p in BASE.rglob("*") if p.is_file() and not should_skip(p))
    if not files:
        print("nothing to package", file=sys.stderr)
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        # Every entry is nested under a single top-level folder so that
        # "unzip anywhere -> open the one folder it created" is foolproof.
        # Without this the archive spills 101 loose files into ~/Downloads and
        # people either open the wrong folder or double-nest it, which is the
        # single most common way this project fails to start on a fresh machine.
        root = BASE.name or "heatshield"
        for f in files:
            z.write(f, Path(root) / f.relative_to(BASE))
        # stamp build info inside the archive
        # Surface the live-state summary at build time: if the queue happens to
        # be empty on the day someone downloads, they should know it is the
        # weather, not a broken install.
        try:
            import pandas as pd

            rd = pd.read_csv(BASE / "data" / "processed" / "risk_daily.csv")
            peak = rd.loc[rd.risk_score.idxmax()]
            state = (
                f"bundled forecast window : {rd.date.min()} -> {rd.date.max()}\n"
                f"peak ward-day risk      : {rd.risk_score.max():.1f} "
                f"({peak.ward_name} on {peak.date})\n"
                f"alert threshold         : 60\n"
            )
        except Exception:                                  # noqa: BLE001
            state = ""

        stamp = (
            f"HeatShield bundle\n"
            f"built: {datetime.now().isoformat(timespec='seconds')}\n"
            f"files: {len(files)}\n"
            f"python: {sys.version.split()[0]}\n"
            f"\n{state}"
            f"\nQUICK START: unzip, then open the guide for your editor -\n"
            f"  ANTIGRAVITY.md   (Google Antigravity - Open VSX marketplace)\n"
            f"  VSCODE.md        (Microsoft Visual Studio Code)\n"
            f"  The code is identical in both editors. They differ only in\n"
            f"  the extension marketplace (Open VSX vs Microsoft) and the\n"
            f"  Windows venv path - both already patched in .vscode/settings.json.\n"
            f"\n"
            f"  ./start.sh     (macOS/Linux)   or   start.bat   (Windows)\n"
            f"  dashboard -> http://localhost:5173\n"
            f"    To put it on GitHub:  ./push-to-github.sh\n"
            f"                          (Windows: double-click push-to-github.bat)\n"
            f"\nRuns offline on first boot: the last forecast is bundled in\n"
            f"data/processed/ and data/cache/. With a connection it pulls a live\n"
            f"one from Open-Meteo (keyless) via:  python -m scripts.refresh\n"
            f"\nThe alert queue is EMPTY when no ward is forecast to reach risk 60.\n"
            f"That is the weather, not a fault - run scripts.hindcast to see how\n"
            f"often the threshold is actually crossed.\n"
        )
        z.writestr(f"{root}/BUNDLE.txt", stamp)

    size_kb = out.stat().st_size / 1024
    print(f"packaged {len(files)} files -> {out}  ({size_kb:.0f} KB)")
    for f in files[:400]:
        print(f"   {f.relative_to(BASE)}")
    if len(files) > 400:
        print(f"   ... and {len(files) - 400} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
